using Optimisarr.Core.Domain;

namespace Optimisarr.Core.Verification;

/// <summary>
/// Everything the pure <see cref="VerificationEvaluator"/> needs to judge a
/// converted output: the outcome of the full-decode health check, the output's
/// own ffprobe result, and the original's properties to compare against. The
/// composition layer gathers these by running ffmpeg/ffprobe; the evaluation
/// itself stays pure and deterministic.
/// </summary>
public sealed record VerificationInput(
    bool DecodeSucceeded,
    string? DecodeError,
    int DecodeErrorCount,
    bool OutputProbeSucceeded,
    string? OutputProbeError,
    string? OutputVideoCodec,
    long OriginalSizeBytes,
    long OutputSizeBytes,
    double? OriginalDurationSeconds,
    double? OutputDurationSeconds,
    int OriginalAudioTrackCount,
    int OutputAudioTrackCount,
    int OriginalSubtitleTrackCount,
    int OutputSubtitleTrackCount,
    bool OriginalIsHdr = false,
    bool OutputIsHdr = false,
    bool HdrConvertedToSdr = false,
    int OriginalMaxAudioChannels = 0,
    int OutputMaxAudioChannels = 0,
    int OriginalMaxAudioSampleRate = 0,
    int OutputMaxAudioSampleRate = 0,
    bool QualityMeasured = false,
    string? QualityError = null,
    QualityScores? QualityScores = null,
    bool LoudnessMeasured = false,
    string? LoudnessError = null,
    double? OriginalLoudnessLufs = null,
    double? OutputLoudnessLufs = null,
    bool TruePeakMeasured = false,
    string? TruePeakError = null,
    double? OriginalTruePeakDbtp = null,
    double? OutputTruePeakDbtp = null,
    string? OriginalColorPrimaries = null,
    string? OutputColorPrimaries = null,
    string? OriginalColorTransfer = null,
    string? OutputColorTransfer = null,
    string? OriginalColorSpace = null,
    string? OutputColorSpace = null,
    double? OriginalVideoStartSeconds = null,
    double? OriginalAudioStartSeconds = null,
    double? OutputVideoStartSeconds = null,
    double? OutputAudioStartSeconds = null,
    bool TimestampsMeasured = false,
    int NonMonotonicTimestampCount = 0,
    string? TimestampRegressionDetail = null,
    double? OutputLastPresentationSeconds = null,
    MediaKind Kind = MediaKind.Video,
    bool AudioReencoded = false,
    bool AudioDownmixed = false,
    // How many audio tracks the kept-languages rule removed on purpose; the retention
    // gate expects exactly that many fewer, never zero audio when the original had any.
    int AudioTracksRemoved = 0,
    int? OriginalWidth = null,
    int? OriginalHeight = null,
    int? OutputWidth = null,
    int? OutputHeight = null,
    bool ImageQualityMeasured = false,
    string? ImageQualityError = null,
    double? ImageSsim = null,
    bool ImageDownscaleRequested = false,
    bool ImageMetadataMeasured = false,
    string? ImageMetadataError = null,
    bool OriginalHasIccProfile = false,
    bool OutputHasIccProfile = false,
    bool OriginalHasExif = false,
    bool OutputHasExif = false,
    bool VideoReencoded = true,
    int OriginalAttachedPictureCount = 0,
    int OutputAttachedPictureCount = 0,
    IReadOnlyDictionary<string, string>? OriginalFormatTags = null,
    IReadOnlyDictionary<string, string>? OutputFormatTags = null,
    string? OriginalVideoCodec = null,
    string? ExpectedVideoCodec = null,
    string? OriginalPixelFormat = null,
    string? OutputPixelFormat = null,
    int? OriginalBitsPerRawSample = null,
    int? OutputBitsPerRawSample = null,
    string? OriginalVideoProfile = null,
    string? OutputVideoProfile = null);
